import type { Course } from "./types";

export const courses: Course[] = [
  {
    slug: "ai-collaboration-foundations",
    code: "DIVE 001",
    eyebrow: "AI COLLABORATION",
    title: "AI 協作第一課：從提問到完成作品",
    shortTitle: "AI 協作第一課",
    summary:
      "用一個真實任務走完理解問題、和 AI 對話、查核內容到交付成果的完整流程。",
    description:
      "這不是一堂背 prompt 的課。我們會從你每天真的會遇到的任務出發，練習判斷什麼適合交給 AI、怎麼補足背景、如何反覆校正，以及在交付前做最後查核。完成後，你會帶走一套可以重複使用的協作節奏。",
    category: "AI 基礎",
    level: "零基礎",
    duration: "2 小時 36 分",
    lessonCount: 8,
    releaseLabel: "隨選即學",
    studentLabel: "1,286 人正在學",
    accessLabel: "免費試看",
    accent: "aqua",
    status: "published",
    featured: true,
    tags: ["提問框架", "內容查核", "實作練習"],
    outcomes: [
      "判斷一個任務適不適合交給生成式 AI",
      "把模糊需求整理成 AI 能理解的工作脈絡",
      "用迭代對話改善輸出，而不是反覆重抽答案",
      "建立交付前的內容查核與風險檢查清單",
    ],
    audience: [
      "剛開始使用 ChatGPT、Gemini 或 Claude 的學習者",
      "想把 AI 用進報告、企劃與日常工作的學生與上班族",
      "不想追逐工具，希望先建立穩定方法的人",
    ],
    instructor: {
      name: "DiveAI 教學團隊",
      role: "AI 共學設計與實作",
      initials: "DA",
      bio: "由大學通識課的師生共同組成，持續把課堂上的 AI 判斷框架整理成人人都能練習的共學內容。",
    },
    sections: [
      {
        id: "start",
        index: "01",
        title: "先理解，再打開工具",
        description: "建立任務判斷框架，知道 AI 能幫上什麼、又不該替你決定什麼。",
        lessons: [
          {
            slug: "why-collaborate-with-ai",
            title: "為什麼我們把 AI 當協作者？",
            duration: "12:40",
            summary:
              "從一個真實案例看見 AI 協作的四個階段，並認識這堂課的練習方式。",
            isPreview: true,
            videoProvider: "youtube",
            videoId: "zjkBMFhNj_g",
          },
          {
            slug: "task-fit-check",
            title: "任務適配檢查：先別急著問 AI",
            duration: "16:20",
            summary: "用風險、可驗證性與資料敏感度判斷任務適配度。",
            isPreview: false,
            videoProvider: "none",
          },
        ],
      },
      {
        id: "context",
        index: "02",
        title: "把背景說清楚",
        description: "從目的、對象、限制與參考資料四個角度，讓 AI 真正理解你的任務。",
        lessons: [
          {
            slug: "context-canvas",
            title: "四格任務脈絡畫布",
            duration: "21:10",
            summary: "把腦中的模糊想法轉成可協作的任務說明。",
            isPreview: false,
            videoProvider: "none",
          },
          {
            slug: "show-dont-tell",
            title: "給範例，比下更多指令有效",
            duration: "18:45",
            summary: "用好例子與反例快速對齊語氣、格式與品質標準。",
            isPreview: false,
            videoProvider: "none",
          },
        ],
      },
      {
        id: "iterate",
        index: "03",
        title: "一起把答案變好",
        description: "讀懂輸出、指出差距，讓每一輪對話都往成果靠近。",
        lessons: [
          {
            slug: "feedback-loop",
            title: "可操作的回饋迴圈",
            duration: "20:30",
            summary: "用保留、刪除、補充、重組四種回饋改善 AI 輸出。",
            isPreview: false,
            videoProvider: "none",
          },
          {
            slug: "compare-options",
            title: "不要只拿一個答案：比較與選擇",
            duration: "17:50",
            summary: "用明確準則比較多個方向，保留自己的判斷權。",
            isPreview: false,
            videoProvider: "none",
          },
        ],
      },
      {
        id: "deliver",
        index: "04",
        title: "查核後再交付",
        description: "檢查來源、偏誤、隱私與最後品質，對成果負責。",
        lessons: [
          {
            slug: "verification-checklist",
            title: "五分鐘內容查核清單",
            duration: "22:15",
            summary: "辨識看似合理的錯誤，補上可靠來源與不確定性說明。",
            isPreview: false,
            videoProvider: "none",
          },
          {
            slug: "final-project",
            title: "實作：完成你的 AI 協作任務",
            duration: "27:10",
            summary: "選一個真實任務，完整走過四階段並留下協作紀錄。",
            isPreview: false,
            videoProvider: "none",
          },
        ],
      },
    ],
  },
  {
    slug: "prompt-to-workflow",
    code: "DIVE 014",
    eyebrow: "WORKFLOW DESIGN",
    title: "不只會下 Prompt：打造可重複的 AI 工作流",
    shortTitle: "打造 AI 工作流",
    summary: "把一次性的好答案，整理成團隊也能跟著做的穩定流程。",
    description:
      "從拆任務、建立模板，到串起資料與人工檢查點，帶你把個人技巧變成可維護的 AI 工作流程。",
    category: "工作應用",
    level: "有使用經驗",
    duration: "3 小時 10 分",
    lessonCount: 10,
    releaseLabel: "每週更新",
    studentLabel: "632 人已收藏",
    accessLabel: "會員課程",
    accent: "navy",
    status: "published",
    featured: false,
    tags: ["流程拆解", "模板設計", "品質控管"],
    outcomes: [
      "辨識流程中適合由 AI 協助的環節",
      "設計可交接、可查核的工作流模板",
      "安排必要的人工審核點與例外處理",
    ],
    audience: ["常態使用 AI 的工作者", "正在建立團隊 AI 規範的管理者"],
    instructor: {
      name: "林怡安",
      role: "產品流程顧問",
      initials: "YA",
      bio: "協助內容與產品團隊把生成式 AI 導入日常流程，關注可交接性與人機協作品質。",
    },
    sections: [
      {
        id: "map",
        index: "01",
        title: "看懂現有流程",
        description: "先找到等待、重工與資訊斷點，再決定 AI 應該放在哪裡。",
        lessons: [
          {
            slug: "workflow-map",
            title: "畫出你的工作流地圖",
            duration: "18:30",
            summary: "用輸入、處理與輸出盤點現有流程。",
            isPreview: true,
            videoProvider: "none",
          },
        ],
      },
    ],
  },
  {
    slug: "ai-visual-storytelling",
    code: "PARTNER 003",
    eyebrow: "VISUAL STORYTELLING",
    title: "讓想法被看見：AI 視覺敘事實戰",
    shortTitle: "AI 視覺敘事實戰",
    summary: "從概念、分鏡到成圖，和合作講師一起完成一組有一致性的視覺作品。",
    description:
      "以實際作品為核心，練習把抽象概念轉成視覺方向、建立一致的生成語言，並完成可公開分享的系列作品。",
    category: "創作實務",
    level: "入門",
    duration: "2 小時 05 分",
    lessonCount: 7,
    releaseLabel: "合作講師課程",
    studentLabel: "458 人感興趣",
    accessLabel: "免費試看",
    accent: "peach",
    status: "published",
    featured: false,
    tags: ["圖像生成", "分鏡", "作品集"],
    outcomes: [
      "把抽象想法整理成可執行的視覺 brief",
      "建立跨張作品一致的畫面語言",
      "整理生成紀錄並做負責任的揭露",
    ],
    audience: ["想開始 AI 圖像創作的人", "需要提案視覺的企劃與學生"],
    instructor: {
      name: "周以晴",
      role: "視覺設計師、合作講師",
      initials: "YC",
      bio: "專注品牌敘事與新媒體視覺，擅長把複雜概念轉成清晰、有情緒的畫面系統。",
    },
    sections: [
      {
        id: "brief",
        index: "01",
        title: "從想法到視覺 brief",
        description: "定義觀眾、訊息與情緒，讓生成不再只是碰運氣。",
        lessons: [
          {
            slug: "visual-brief",
            title: "一頁視覺 brief",
            duration: "14:20",
            summary: "用六個欄位整理你的視覺目標。",
            isPreview: true,
            videoProvider: "none",
          },
        ],
      },
    ],
  },
  {
    slug: "responsible-ai-everyday",
    code: "DIVE 020",
    eyebrow: "RESPONSIBLE AI",
    title: "安心用 AI：日常資料、版權與查核指南",
    shortTitle: "安心用 AI",
    summary: "用具體情境辨識資料、著作權與錯誤資訊風險，建立自己的安全界線。",
    description:
      "從上傳會議紀錄、引用 AI 生成內容到分享圖像，整理每個人都會遇到的風險與可執行做法。",
    category: "AI 素養",
    level: "全程度",
    duration: "1 小時 40 分",
    lessonCount: 6,
    releaseLabel: "預計 9 月上線",
    studentLabel: "開放到課提醒",
    accessLabel: "即將推出",
    accent: "mint",
    status: "coming-soon",
    featured: false,
    tags: ["隱私", "版權", "資訊查核"],
    outcomes: [
      "辨識不適合提供給公開 AI 服務的資料",
      "正確說明 AI 在作品中的參與方式",
      "為高風險內容建立查核流程",
    ],
    audience: ["所有日常 AI 使用者", "教師、學生與內容工作者"],
    instructor: {
      name: "DiveAI × 合作顧問",
      role: "AI 素養與數位權利",
      initials: "AI",
      bio: "由 DiveAI 教學團隊與外部專業顧問共同規劃，將抽象規範整理為日常可以採用的行動清單。",
    },
    sections: [
      {
        id: "data",
        index: "01",
        title: "資料可以交給 AI 嗎？",
        description: "認識敏感資料、平台條款與替代做法。",
        lessons: [
          {
            slug: "data-boundary",
            title: "三層資料界線",
            duration: "16:00",
            summary: "在輸入前先替資料分類。",
            isPreview: false,
            videoProvider: "none",
          },
        ],
      },
    ],
  },
];
