-- 共學牆文章資料表。到 Supabase 專案的 SQL editor 貼上整段執行即可。
--
-- 欄位命名對齊 app/lib/wall/mock-posts.ts 的 WallPost 型別（camelCase 換成
-- snake_case），app/lib/wall/wall-state-context.tsx 讀寫時會做轉換。
create table if not exists public.articles (
  id bigint generated by default as identity primary key,
  kind text not null check (kind in ('project', 'note', 'agent')),
  title text not null,
  body_md text not null default '',
  cover_url text not null default '',
  links jsonb not null default '[]'::jsonb, -- [{ "label": "...", "url": "..." }]
  scene text[] not null default '{}',       -- 課業／實習／職涯／日常
  tech_tags text[] not null default '{}',
  author_name text not null default '',
  author_avatar_url text not null default '',
  like_count integer not null default 0,
  status text not null check (status in ('draft', 'published')) default 'draft',
  created_at date not null default current_date
);

create index if not exists articles_status_created_at_idx
  on public.articles (status, created_at desc);

-- 開 Realtime，前台／後台開在不同分頁或不同裝置時，其中一邊改資料，
-- 另一邊會透過 postgres_changes 訂閱即時收到更新（不用手動重新整理）。
alter publication supabase_realtime add table public.articles;

alter table public.articles enable row level security;

-- 目前後台（/admin/wall）還沒有登入門檻（產品決策：先不做，之後接權限
-- 系統再補），所以這裡的 RLS 先開放 anon 角色可以讀寫所有文章（含草稿），
-- 跟現在「後台任何人都能改」的風險等級一致，不是新增的風險，但要注意：
-- 這代表任何人只要有 anon public key（前端程式碼本來就看得到）就能直接
-- 呼叫 Supabase API 新增／修改／刪除文章，不是只能透過後台介面操作。
-- 之後要收斂權限的話，把下面這幾條 policy 換成「只有登入且有權限的使用者
-- 才能 insert/update/delete，所有人都能 select 已發布文章」即可。
create policy "articles_select_all" on public.articles
  for select using (true);

create policy "articles_insert_all" on public.articles
  for insert with check (true);

create policy "articles_update_all" on public.articles
  for update using (true) with check (true);

create policy "articles_delete_all" on public.articles
  for delete using (true);
